Repository psantosh16/abhiyaan_home, pull requests merged in 2023-03, with the labels that each got.

#21 Navbar Updates and Image overlay issue reolved
  src/components/Navbar.jsx
  src/utils/BtmImg.jsx
Labels: enhancement

#22 Sponsers added
  public/sponsers/Clydelogo.png
  public/sponsers/eti.png
  public/sponsers/hotmuggs.webp
  src/components/Navbar.jsx
  src/components/Sponsers.jsx
  src/index.css
  src/pages/About.jsx
  src/pages/Home.jsx
Labels: documentation, enhancement

#25 Preloader.jsx added and finished
  package-lock.json
  package.json
  src/App.jsx
  src/features/preloader/Preloader.jsx
  src/features/preloader/Preloader.scss
  src/index.css
  src/pages/Home.jsx
Labels: documentation, enhancement

#26 bug fixes
  src/App.jsx
  src/Gallery/components/Gallery.css
  src/Gallery/components/YearsPage.jsx
  src/components/Logo.jsx
  src/components/Navbar.jsx
  src/components/Sponsers.jsx
  src/features/preloader/Preloader.scss
  src/index.css
  src/pages/Home.jsx
  src/utils/TopImg.jsx
Labels: bug, documentation, enhancement

#28 Map component added
  package-lock.json
  package.json
  src/components/Map.jsx
  src/components/Navbar.jsx
  src/components/Sponsers.jsx
  src/pages/Home.jsx
Labels: enhancement

#29 Contact added
  src/components/Map.jsx
  src/components/Navbar.jsx
  src/components/Sponsers.jsx
  src/pages/About.jsx
  src/pages/Contact.jsx
  src/pages/Home.jsx
Labels: enhancement

#30 Footer added and unused dependency removed
  index.html
  package-lock.json
  package.json
  src/components/Footer.jsx
  src/pages/Home.jsx
  src/utils/MarqueeText.jsx
Labels: enhancement
